package lexer;

public enum Symbol
{
	SEMICOLON, RIGHTPAREN, LEFTPAREN, RIGHTSQUARE, LEFTSQUARE,RIGHTBRACE, LEFTBRACE, ASSIGN, EQUALS, NOTEQUAL, LESS, GREATER, GOREQUAL, LOREQUAL, 
	PLUS, MINUS, PLUSPLUS, MINUSMINUS, PLUSEQUALS, MINUSEQUALS, TIMES, SLASH, TIMESEQUALS, DIVIDEDEQUALS, NAME,MODULO, MODULOEQUALS, DOT, RIGHTARROW, 
	OR, AND, XOR, NOT, RIGHTSHIFT, LEFTSHIFT, RIGHTSHIFTEQUALS, LEFTSHIFTEQUALS, BITXOR, BITXOREQUALS, BITNOT, BITOR, BITOREQUALS, BITNOTEQUALS, 
	BITAND, BITANDEQUALS, NEW, DELETE, PUBLIC, PRIVATE, PROTECTED, STATIC, CLASS, COLON, COLONCOLON
	
}
